/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs245project;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author michael
 */
public class ColorGamePanel extends javax.swing.JPanel {
    private String[] colorName = {"Red", "Yellow", "Green", "Blue", "Pink"};
    private Color[] colors = {Color.RED, Color.YELLOW, Color.GREEN, Color.BLUE, Color.PINK};
    private Random random = new Random();
    
    private int totalScore;

    /**
     * Creates new form ColorGamePanel
     */
    public ColorGamePanel(int totalScore) {
        initComponents();
        this.totalScore = totalScore;
        
        dateLabel.setBorder(BorderFactory.createLineBorder(Color.WHITE, 2));
        //This next line exists to populate the date upon launch of game. If not here,
        //date populates as "jLabel2" for one runtime second then does date properly.
        dateLabel.setText(new SimpleDateFormat("MMMM d, yyyy HH:mm:ss").format(new Date()));
        setDate();
        
        scoreLabel.setText("Total Score: " + String.valueOf(totalScore));
        colorNameLabel.setText(colorName[random.nextInt(colorName.length)]);
        colorNameLabel.setForeground(colors[random.nextInt(colors.length)]);
        
        displayImagesRandomly();
    }
    
    private void displayImagesRandomly() {
        
    }
    
    // method: setDate
    // purpose: The purpose of this method is to start a timer event to display
    // the correct date updated each second at the top right corner of the screen.
    public void setDate() {  
        ActionListener date = (java.awt.event.ActionEvent e) -> {
            dateLabel.setText(new SimpleDateFormat("MMMM d, yyyy HH:mm:ss").format(new Date()));
        };
        new javax.swing.Timer(1000, date).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        colorNameLabel = new javax.swing.JLabel();
        innerJPanel = new javax.swing.JPanel();
        ballOne = new javax.swing.JButton();
        ballTwo = new javax.swing.JButton();
        ballThree = new javax.swing.JButton();
        ballFour = new javax.swing.JButton();
        ballFive = new javax.swing.JButton();

        setLayout(null);

        dateLabel.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        dateLabel.setText("jLabel2");
        add(dateLabel);
        dateLabel.setBounds(380, 10, 210, 20);

        scoreLabel.setText("jLabel3");
        add(scoreLabel);
        scoreLabel.setBounds(20, 10, 150, 16);

        colorNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        colorNameLabel.setText("jLabel1");
        add(colorNameLabel);
        colorNameLabel.setBounds(250, 50, 109, 16);

        ballOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/redball.png"))); // NOI18N
        ballOne.setBorderPainted(false);
        ballOne.setContentAreaFilled(false);
        ballOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ballOneMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ballOneMouseEntered(evt);
            }
        });
        ballOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ballOneActionPerformed(evt);
            }
        });

        ballTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/redball.png"))); // NOI18N
        ballTwo.setBorderPainted(false);
        ballTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ballTwoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ballTwoMouseEntered(evt);
            }
        });
        ballTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ballTwoActionPerformed(evt);
            }
        });

        ballThree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/redball.png"))); // NOI18N
        ballThree.setBorderPainted(false);
        ballThree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ballThreeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ballThreeMouseEntered(evt);
            }
        });
        ballThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ballThreeActionPerformed(evt);
            }
        });

        ballFour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/redball.png"))); // NOI18N
        ballFour.setBorderPainted(false);
        ballFour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ballFourMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ballFourMouseEntered(evt);
            }
        });
        ballFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ballFourActionPerformed(evt);
            }
        });

        ballFive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/redball.png"))); // NOI18N
        ballFive.setBorderPainted(false);
        ballFive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ballFiveMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ballFiveMouseEntered(evt);
            }
        });
        ballFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ballFiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout innerJPanelLayout = new javax.swing.GroupLayout(innerJPanel);
        innerJPanel.setLayout(innerJPanelLayout);
        innerJPanelLayout.setHorizontalGroup(
            innerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerJPanelLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(ballFour)
                .addGap(111, 111, 111)
                .addComponent(ballFive)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(innerJPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(ballOne)
                .addGap(56, 56, 56)
                .addComponent(ballTwo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(ballThree)
                .addGap(55, 55, 55))
        );
        innerJPanelLayout.setVerticalGroup(
            innerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerJPanelLayout.createSequentialGroup()
                .addGroup(innerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(innerJPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ballThree))
                    .addGroup(innerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, innerJPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(ballTwo))
                        .addGroup(innerJPanelLayout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(ballOne))))
                .addGroup(innerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(innerJPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(ballFour))
                    .addGroup(innerJPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ballFive)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        add(innerJPanel);
        innerJPanel.setBounds(6, 76, 585, 334);
    }// </editor-fold>//GEN-END:initComponents

    private void ballOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ballOneActionPerformed
        
    }//GEN-LAST:event_ballOneActionPerformed

    private void ballTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ballTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ballTwoActionPerformed

    private void ballThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ballThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ballThreeActionPerformed

    private void ballFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ballFourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ballFourActionPerformed

    private void ballFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ballFiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ballFiveActionPerformed

    private void ballOneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ballOneMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ballOneMouseEntered

    private void ballTwoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ballTwoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ballTwoMouseEntered

    private void ballOneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ballOneMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ballOneMouseExited

    private void ballTwoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ballTwoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ballTwoMouseExited

    private void ballThreeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ballThreeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ballThreeMouseEntered

    private void ballThreeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ballThreeMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ballThreeMouseExited

    private void ballFourMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ballFourMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ballFourMouseEntered

    private void ballFourMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ballFourMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ballFourMouseExited

    private void ballFiveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ballFiveMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ballFiveMouseEntered

    private void ballFiveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ballFiveMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ballFiveMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ballFive;
    private javax.swing.JButton ballFour;
    private javax.swing.JButton ballOne;
    private javax.swing.JButton ballThree;
    private javax.swing.JButton ballTwo;
    private javax.swing.JLabel colorNameLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JPanel innerJPanel;
    private javax.swing.JLabel scoreLabel;
    // End of variables declaration//GEN-END:variables
}
