/*************************************************************
 *      file: HangmanResultFrame.java
 *      author: Michael Muinos
 *      class: CS 245 - Programming Graphical User Interfaces
 *  
 *      assignment: Quarter Project, Checkpoint # 1
 *      date last modified: 8/8/16
 * 
 *      purpose: The purpose of this class is to create a new JFrame
 *      object that displays to the user the result of the hangman
 *      game (whether they won, lost, or skipped).
 ************************************************************/
package cs245project;

import java.awt.Font;

public class HangmanResultFrame extends javax.swing.JFrame {

    // constructor: HangmanresultFrame
    // purpose: the following constructor will create a new JFrame object.
    // Additionally, it passes in the result text and users score
    // from the hangman game and updates the labels.
    public HangmanResultFrame(String labelText, int score) {
        initComponents();
        resultLabel.setText(labelText);
        //resultLabel.setSize(100, 100);
        resultLabel.setFont(new Font("Courier New", Font.ITALIC, 25));
        scoreLabel.setText("Total Score: " + String.valueOf(score));
    }
    
    // method:setResultFrameAttributes
    // purpose: This method will force the Jframe to be displayed
    // in the center of the screen and make it seen.
    public void setResultFrameAttributes() {
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hangmanLabel = new javax.swing.JLabel();
        mainMenuButton = new javax.swing.JButton();
        scoreLabel = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hangmanLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/HangmanLogo1.png"))); // NOI18N
        hangmanLabel.setText("Hangman");
        hangmanLabel.setPreferredSize(new java.awt.Dimension(150, 62));

        mainMenuButton.setText("Back To Main Menu");
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        scoreLabel.setText("jLabel1");

        resultLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(hangmanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(mainMenuButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(scoreLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(resultLabel)))
                .addGap(241, 241, 241))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(hangmanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(resultLabel)
                .addGap(39, 39, 39)
                .addComponent(scoreLabel)
                .addGap(29, 29, 29)
                .addComponent(mainMenuButton)
                .addGap(156, 156, 156))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // method: mainMenuButtonActionPerformed
    // purpose: this method was auto-generated by NetBeans. It will create a new
    // main menu jframe and dispose of the current frame.
    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        MainMenuFrame mainMenu = new MainMenuFrame();
        mainMenu.setMainMenuAttributes();
        this.dispose();
    }//GEN-LAST:event_mainMenuButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hangmanLabel;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel scoreLabel;
    // End of variables declaration//GEN-END:variables
}
